### ISSUE TITLE
Improve performance of Curatescape theme on PageSpeed Insights

### ISSUE THREAD

**Issue by elipousson** [CPHDH/theme-curatescape#2]
I tested [Cleveland Historical](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fclevelandhistorical.org%2F) and [Explore Baltimore Heritage](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fexplore.baltimoreheritage.org%2F) with PageSpeed Insights and spotted a handful of issues.
- [ ] Eliminate render-blocking JavaScript and CSS in above-the-fold content
- [ ] Optimize images
- [ ] Minify screen.css
- [ ] Minify check-width.js
- [ ] Leverage browser caching (maybe add svg files to cached filetypes on .htaccess?)

![PageSpeed Insights results for clevelandhistorical.org](https://cloud.githubusercontent.com/assets/931136/13747271/dc2e9cb4-e9cd-11e5-83a5-eed7b0d2090e.png)

**Comment by csudigitalhumanities** [comment]
Most of these are improved upon in the new version, which defers JS and CSS loading wherever possible. Content image optimizations will need to be done offline or via further development of Omeka (e.g. through plugins, site settings, etc). And server configurations like .htaccess additions or SSL certs (which are also now factored in on some audits, e.g. in Chrome Dev tools) are out of scope here.
